const ACTIONS = {
    SERVER_ROOM_JOINED: 'socket_ROOM_JOINED',
    CLIENT_ROOM_JOINED_BRODCAST: 'CLIENT_ROOM_JOINED_BRODCAST',

    REQUEST_OFFER: 'REQUEST_OFFER',
    SEND_OFFER: 'SEND_OFFER',
    SEND_ANSWER: 'SEND_ANSWER',
};

export default ACTIONS;
